Project2BurgerMenu/Areas/Admin/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2BurgerMenu.Areas.Admin.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: Admin/AdminLayout
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView("PartialHead");
        }

        public PartialViewResult PartialNavBar()
        {
            return PartialView();
        }

        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
    }


}

Project2BurgerMenu/Areas/Admin/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<!--Header Start -->
@Html.Action("PartialHead", "AdminLayout", "Admin")
<!-- End Header -->

<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        @Html.Action("PartialNavBar", "AdminLayout", "Admin")
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">

            <!-- partial:../../partials/_sidebar.html -->
            @Html.Action("PartialSidebar", "AdminLayout", "Admin")
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">

                        @RenderBody()

                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap dashboard templates</a> from Bootstrapdash.com</span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="../../vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="../../js/off-canvas.js"></script>
    <script src="../../js/hoverable-collapse.js"></script>
    <script src="../../js/template.js"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->
</body>

</html>

Project2BurgerMenu/Areas/Admin/Views/AdminLayout/PartialHead.cshtml
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Burger Admin Paneli</title>
    <!-- base:css -->
    <link rel="stylesheet" href="/regal/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/regal/vendors/feather/feather.css">
    <link rel="stylesheet" href="/regal/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/regal/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="/regal/images/favicon.png" />
</head>

Project2BurgerMenu/Areas/Admin/Views/AdminLayout/PartialNavBar.cshtml
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="../../index.html"><img src="~/regal/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="../../index.html"><img src="~/regal/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav mr-lg-2">
            <li class="nav-item nav-search d-none d-lg-block">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="search">
                            <i class="icon-search"></i>
                        </span>
                    </div>
                    <input type="text" class="form-control" placeholder="Aranacak Kelimeleri Giriniz..." aria-label="search" aria-describedby="search">
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-lg-flex d-none">
                <button type="button" class="btn btn-info font-weight-bold">+ Yeni Rezervasyon Olustur</button>
            </li>
            <li class="nav-item dropdown d-flex">
                <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-air-play mx-0"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="../../images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                David Grey
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                The meeting is cancelled
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="../../images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Tim Cook
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                New product launch
                            </p>
                        </div>
                    </a>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="../../images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content flex-grow">
                            <h6 class="preview-subject ellipsis font-weight-normal">
                                Johnson
                            </h6>
                            <p class="font-weight-light small-text text-muted mb-0">
                                Upcoming board meeting
                            </p>
                        </div>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown d-flex mr-4 ">
                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="icon-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <p class="mb-0 font-weight-normal float-left dropdown-header">Settings</p>
                    <a class="dropdown-item preview-item">
                        <i class="icon-head"></i> Profile
                    </a>
                    <a class="dropdown-item preview-item">
                        <i class="icon-inbox"></i> Logout
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown mr-4 d-lg-flex d-none">
                <a class="nav-link count-indicatord-flex align-item s-center justify-content-center" href="#">
                    <i class="icon-grid"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

Project2BurgerMenu/Areas/Admin/Views/AdminLayout/PartialSidebar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="user-profile">
        <div class="user-image">
            <img src="~/regal/images/faces/face28.png">
        </div>
        <div class="user-name">
            Yasin Kereci
        </div>
        <div class="user-designation">
            Software Developer
        </div>
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="../../index.html">
                <i class="icon-box menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/forms/basic_elements.html">
                <i class="icon-file menu-icon"></i>
                <span class="menu-title">Kategoriler</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/charts/chartjs.html">
                <i class="icon-pie-graph menu-icon"></i>
                <span class="menu-title">Ürünler</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/tables/basic-table.html">
                <i class="icon-command menu-icon"></i>
                <span class="menu-title">Rezervasyonlar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Mesajlar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Hakkimizda</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Referanslar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Istatistikler</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Raporlar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Kredi Karti</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Ayarlar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/feather-icons.html">
                <i class="icon-help menu-icon"></i>
                <span class="menu-title">Cikis Yap</span>
            </a>
        </li>
        
    </ul>
</nav>