Project2BurgerMenu/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2BurgerMenu.Entities;
using Project2BurgerMenu.Context;

namespace Project2BurgerMenu.Controllers
{
    public class DefaultController : Controller
    {
        BurgerMenuContext db = new BurgerMenuContext(); 
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {

            return PartialView();   
        }

        public PartialViewResult PartialNavBar()
        {
            return PartialView();
        }

        public PartialViewResult PartialAbout()
        {
            return PartialView();
        }
        public PartialViewResult TodaysOffer()
        {
            var deal = db.Products.Where(x => x.DealOfTheDay == true).ToList(); 
            return PartialView(deal);
        }
        public PartialViewResult PartialMenu()
        {   
            var values = db.Products.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialCategory() 
        {
            var values = db.Categories.Take(6).ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialGallery()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialScripts() {
            return PartialView();
        }

        [HttpGet]
        public PartialViewResult PartialReservation()
        {
            return PartialView();
        }


        [HttpPost]
        public PartialViewResult PartialReservation(Reservation reservation)
        {
            reservation.ReservationStatus = "Beklemede";
            reservation.PeopleCount = 0;
            reservation.ReservationDate = DateTime.Now;    
            db.Reservations.Add(reservation);
            db.SaveChanges();
            return PartialView();
        }
    }
}

Project2BurgerMenu/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
@Html.Action("PartialHead", "Default")
<body data-spy="scroll" data-target="#site-navbar" data-offset="200">

@Html.Action("PartialNavBar", "Default") 
@Html.Action("PartialAbout", "Default") 

    
    <!-- END section -->


    @Html.Action("TodaysOffer", "Default")  
    <!-- END section -->

    @Html.Action("PartialMenu", "Default")
    <!-- END section -->

    
    <!-- END section -->

    @Html.Action("PartialGallery", "Default")
    <!-- END section -->

    <section class="site-section bg-light" id="section-contact">
        <div class="container">
            <div class="row">

                <div class="col-md-12 text-center mb-5 site-animate">
                    <h2 class="display-4">Get In Touch</h2>
                    <div class="row justify-content-center">
                        <div class="col-md-7">
                            <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-7 mb-5 site-animate">
                    <form action="" method="post">
                        <div class="form-group">
                            <label for="name" class="sr-only">Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="text" class="form-control" id="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label for="message" class="sr-only">Message</label>
                            <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Write your message"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary btn-lg" value="Send Message">
                        </div>
                    </form>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-4 site-animate">
                    <p><img src="images/about_img_1.jpg" alt="" class="img-fluid"></p>
                    <p class="text-black">
                        Address: <br> 121 Street, Melbourne Victoria <br> 3000 Australia <br> <br>
                        Phone: <br> 90 987 65 44 <br> <br>
                        Email: <br> <a href="mailto:info@yoursite.com">info@yoursite.com</a>
                    </p>

                </div>

            </div>
        </div>
    </section>
    <div id="map"></div>
    <!-- END section -->


    @Html.Action("PartialFooter", "Default")    




    <!-- Modal -->
    @Html.Action("PartialReservation", "Default") 

    <!-- END Modal -->
    <!-- loader -->
 
    <!-- END loader -->

    @Html.Action("PartialScripts", "Default") 
    <!-- END scripts -->    


</body>
</html>

Project2BurgerMenu/Views/Default/PartialAbout.cshtml
<section class="site-section" id="section-about">
    <div class="container">
        <div class="row">
            <div class="col-md-5 site-animate mb-5">
                <h4 class="site-sub-title">Our Story</h4>
                <h2 class="site-primary-title display-4">Welcome</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>

                <p class="mb-4">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                <p><a href="#" class="btn btn-secondary btn-lg">Learn More About Us</a></p>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-6 site-animate img" data-animate-effect="fadeInRight">
                <img src="images/about_img_1.jpg" alt="Free Template by colorlib.com" class="img-fluid">
            </div>
        </div>
    </div>
</section>

Project2BurgerMenu/Views/Default/PartialCategory.cshtml
@model List<Project2BurgerMenu.Entities.Category>

<ul class="nav site-tab-nav nav-pills mb-5" id="pills-tab" role="tablist">
    @foreach(var item in Model) {
    <li class="nav-item site-animate">
        <a class="nav-link active" id="pills-breakfast-tab" data-toggle="pill" href="#pills-breakfast" role="tab" aria-controls="pills-breakfast" aria-selected="true">@item.CategoryName"</a>
    </li>
     }

</ul>

Project2BurgerMenu/Views/Default/PartialFooter.cshtml
<footer class="site-footer site-bg-dark site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4 site-animate">
                        <h2 class="site-heading-2">About Us</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque, similique, delectus blanditiis odit expedita amet. Sed labore ipsum vel dolore, quis, culpa et magni autem sequi facere eos tenetur, ex?</p>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3 site-animate">
                        <div class="site-footer-widget mb-4">
                            <h2 class="site-heading-2">The Restaurant</h2>
                            <ul class="list-unstyled">
                                <li><a href="#" class="py-2 d-block">About Us</a></li>
                                <li><a href="#" class="py-2 d-block">Chefs</a></li>
                                <li><a href="#" class="py-2 d-block">Events</a></li>
                                <li><a href="#" class="py-2 d-block">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 site-animate">
                        <div class="site-footer-widget mb-4">
                            <h2 class="site-heading-2">Useful links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#" class="py-2 d-block">Foods</a></li>
                                <li><a href="#" class="py-2 d-block">Drinks</a></li>
                                <li><a href="#" class="py-2 d-block">Breakfast</a></li>
                                <li><a href="#" class="py-2 d-block">Brunch</a></li>
                                <li><a href="#" class="py-2 d-block">Dinner</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 site-animate">
                        <div class="site-footer-widget mb-4">
                            <h2 class="site-heading-2">Useful links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#" class="py-2 d-block">Foods</a></li>
                                <li><a href="#" class="py-2 d-block">Drinks</a></li>
                                <li><a href="#" class="py-2 d-block">Breakfast</a></li>
                                <li><a href="#" class="py-2 d-block">Brunch</a></li>
                                <li><a href="#" class="py-2 d-block">Dinner</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row site-animate">
            <div class="col-md-12 text-center">
                <div class="site-footer-widget mb-4">
                    <ul class="site-footer-social list-unstyled ">
                        <li class="site-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="site-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="site-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-12 text-center">
                <p>
                    &copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> &amp; distributed by <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

Project2BurgerMenu/Views/Default/PartialGallery.cshtml
<section class="site-section" id="section-gallery">
    <div class="container">
        <div class="row site-custom-gutters">

            <div class="col-md-12 text-center mb-5 site-animate">
                <h2 class="display-4">Gallery</h2>
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_1.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_1.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>
            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_2.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_2.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>
            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_3.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_3.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>

            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_2.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_2.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>
            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_3.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_3.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>
            <div class="col-md-4 site-animate">
                <a href="/eatwell-master/images/menu_1.jpg" class="site-thumbnail image-popup">
                    <img src="images/menu_1.jpg" alt="Free Template by colorlib.com" class="img-fluid">
                </a>
            </div>

        </div>
    </div>
</section>

Project2BurgerMenu/Views/Default/PartialHead.cshtml
<head>
    <title>Colorlib Template - EatWell</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700|Raleway" rel="stylesheet">

    <link rel="stylesheet" href="/eatwell-master/css/bootstrap.min.css">
    <link rel="stylesheet" href="/eatwell-master/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/eatwell-master/css/animate.css">

    <link rel="stylesheet" href="/eatwell-master/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/eatwell-master/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/eatwell-master/css/magnific-popup.css">

    <link rel="stylesheet" href="/eatwell-master/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/eatwell-master/css/jquery.timepicker.css">



    <link rel="stylesheet" href="/eatwell-master/css/icomoon.css">
    <link rel="stylesheet" href="/eatwell-master/css/style.css">
</head>

Project2BurgerMenu/Views/Default/PartialMenu.cshtml
@model List<Project2BurgerMenu.Entities.Product>

@{
    int count = 0;
}

<section class="site-section" id="section-menu">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center mb-5 site-animate">
                <h2 class="display-4">Delicious Menu</h2>
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    </div>
                </div>
            </div>

            <div class="col-md-12 text-center">

                @Html.Action("PartialCategory", "Default")


                <div class="tab-content text-left">
                    <div class="tab-pane fade show active" id="pills-breakfast" role="tabpanel" aria-labelledby="pills-breakfast-tab">
                        <div class="row">

                            @foreach (var item in Model)
                            {
                                count++;

                                if (count % 2 == 1)
                                {



                                    <div class="col-md-6 site-animate">
                                        <div class="media menu-item">
                                            <img class="mr-3" src="@item.ImageUrl" class="img-fluid" alt="Free Template by colorlib.com">
                                            <div class="media-body">
                                                <h5 class="mt-0">@item.ProductName</h5>
                                                <p>@item.ProductDescription</p>
                                                <h6 class="text-primary menu-price">@item.ProductPrice CH</h6>
                                            </div>
                                        </div>



                                    </div>
                                }
                                else
                                {
                                    <div class="col-md-6 site-animate">
                                        <div class="media menu-item">
                                            <img class="mr-3" src="@item.ImageUrl" class="img-fluid" alt="Free Template by colorlib.com">
                                            <div class="media-body">
                                                <h5 class="mt-0">@item.ProductName</h5>
                                                <p>@item.ProductDescription</p>
                                                <h6 class="text-primary menu-price">@item.ProductPrice CH</h6>
                                            </div>
                                        </div>


                                    </div>

                                }
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

Project2BurgerMenu/Views/Default/PartialNavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark site_navbar bg-dark site-navbar-light" id="site-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">EatWell</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#site-nav" aria-controls="site-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="site-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="#section-home" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#section-about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="#section-offer" class="nav-link">Offer</a></li>
                <li class="nav-item"><a href="#section-menu" class="nav-link">Menu</a></li>
                <li class="nav-item"><a href="#section-news" class="nav-link">News</a></li>
                <li class="nav-item"><a href="#section-gallery" class="nav-link">Gallery</a></li>
                <li class="nav-item"><a href="#section-contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

<section class="site-cover" style="background-image: url(/eatwell-master/images/bg_3.jpg);" id="section-home">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center site-vh-100">
            <div class="col-md-12">
                <h1 class="site-heading site-animate mb-3">Welcome To EatWell</h1>
                <h2 class="h5 site-subheading mb-5 site-animate">Come and eat well with our delicious &amp; healthy foods.</h2>
                <p><a href="https://colorlib.com/" target="_blank" class="btn btn-outline-white btn-lg site-animate" data-toggle="modal" data-target="#reservationModal">Reservation</a></p>
            </div>
        </div>
    </div>
</section>
<!-- END section -->

Project2BurgerMenu/Views/Default/PartialReservation.cshtml
<div class="modal fade" id="reservationModal" tabindex="-1" role="dialog" aria-labelledby="reservationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bg-image" style="background-image: url(/eatwell-master/images/reservation_1.jpg);"></div>
                    </div>
                    <div class="col-lg-12 p-5">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <small>CLOSE </small><span aria-hidden="true">&times;</span>
                        </button>
                        <h1 class="mb-4">Reserve A Table</h1>
                        <form action="#" method="post">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="m_fname">First Name</label>
                                    <input type="text" name="Name" class="form-control" id="m_fname">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="m_lname">Last Name</label>
                                    <input type="text" name="Surname" class="form-control" id="m_lname">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="m_email">Email</label>
                                    <input type="email" name="Email" class="form-control" id="m_email">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="m_people">How Many People</label>
                                    <select name="" name="PeopleCount" id="m_people" class="form-control">
                                        <option value="1">1 People</option>
                                        <option value="2">2 People</option>
                                        <option value="3">3 People</option>
                                        <option value="4+">4+ People</option>
                                    </select>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="m_phone">Phone</label>
                                    <input type="text" name="Phone" class="form-control" id="m_phone">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="m_date">Date</label>
                                    <input type="text" name="ReservationDate" class="form-control" id="m_date">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="m_time">Time</label>
                                    <input type="text" name="Time" class="form-control" id="m_time">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="m_message">Message</label>
                                    <textarea class="form-control" name="Message" id="m_message" cols="30" rows="7"></textarea>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <input type="submit" name="ReservationStatus" class="btn btn-primary btn-lg btn-block" value="Reserve Now">
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

Project2BurgerMenu/Views/Default/PartialScripts.cshtml
<div id="site-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


<script src="/eatwell-master/js/jquery.min.js"></script>
<script src="/eatwell-master/js/popper.min.js"></script>
<script src="/eatwell-master/js/bootstrap.min.js"></script>
<script src="/eatwell-master/js/jquery.easing.1.3.js"></script>
<script src="/eatwell-master/js/jquery.waypoints.min.js"></script>
<script src="/eatwell-master/js/owl.carousel.min.js"></script>
<script src="/eatwell-master/js/jquery.magnific-popup.min.js"></script>

<script src="/eatwell-master/js/bootstrap-datepicker.js"></script>
<script src="/eatwell-master/js/jquery.timepicker.min.js"></script>

<script src="/eatwell-master/js/jquery.animateNumber.min.js"></script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="/eatwell-master/js/google-map.js"></script>

<script src="/eatwell-master/js/main.js"></script>

Project2BurgerMenu/Views/Default/TodaysOffer.cshtml
@model List<Project2BurgerMenu.Entities.Product>  

<section class="site-section bg-light" id="section-offer">
    <div class="container">

        <div class="row">
            <div class="col-md-12 text-center mb-5 site-animate">
                <h4 class="site-sub-title">Our Offers</h4>
                <h2 class="display-4">Sizler icin essiz lezzetler</h2>
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <p class="lead">Haftanin hergünü belli günlerde en az %20 indirim, günün her saatinde iceceklerde %15 indirim ile sizleri restoranimiza bekliyoruz.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel site-owl">

                    @foreach(var item in Model) {
                    <div class="item">
                        <div class="media d-block mb-4 text-center site-media site-animate border-0">
                            <img src="@item.ImageUrl" style="height:240px" alt="Free Template by colorlib.com" class="img-fluid">
                            <div class="media-body p-md-5 p-4">
                                <h5 class="text-primary">@item.ProductPrice</h5>
                                <h5 class="mt-0 h4">@item.ProductName</h5>
                                <p class="mb-4">@item.ProductDescription</p>

                                <p class="mb-0"><a href="#" class="btn btn-primary btn-sm">Order Now!</a></p>
                            </div>
                        </div>
                    </div>
                    }

                   

                </div>
            </div>

        </div>
    </div>
</section>